sudo: false

language: node_js

env:
  - DB=postgres://postgres@localhost/testing_db

node_js:
  - node

variables:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 

cache:
  directories:
    - node_modules

services:
  - postgresql

before_install:
  - npm config set spin false

before_script:
  - psql -c 'CREATE DATABASE testing_db;' -U postgres
  - psql -c 'CREATE TABLE public.questions (id serial NOT NULL, username character varying NOT NULL, question character varying NOT NULL, answers character varying[] NOT NULL, viewed integer NOT NULL, "time" date NOT NULL, PRIMARY KEY (id));' -U postgres
  - psql -c 'CREATE TABLE public.users (id serial NOT NULL, username character varying NOT NULL, email character varying NOT NULL, password character varying NOT NULL, answers integer NOT NULL, signupdate date NOT NULL, PRIMARY KEY (id));' -U postgres
  - psql -c "INSERT INTO questions (username, question, answers, viewed, time) VALUES('demouser', 'What is travis', '{}', 0, NOW());" -U postgres

script:
  - npm test
