sudo: false

language: node_js

env:
  - DB=postgres://fgxmlcmztjlnqa:78ed6f0c9e151eb1f3fbb6e8a7a50ba3d4a9bf471e6498ea527119a2169ea645@ec2-107-20-167-11.compute-1.amazonaws.com:5432/da9ssf8703fkcj

node_js:
  - node

variables:
  POSTGRES_USER: fgxmlcmztjlnqa
  POSTGRES_PASSWORD: 78ed6f0c9e151eb1f3fbb6e8a7a50ba3d4a9bf471e6498ea527119a2169ea645

cache:
  directories:
    - node_modules

services:
  - postgresql

before_install:
  - npm config set spin false

script:
  - npm test
